name: testing yaml
run-name: I am Testing yaml
on:
  push:
    branches: [main]

jobs:
   First_Job:
    runs-on: ubuntu-latest
      steps:
	-name: compile
	  run: javac -d bin src/HelloWorld.java
	-name: Running
          run: java -cp bin helloWorld
