name: testing yaml
run-name: I am Testing yaml
on:
  push:
    branches: [main]

jobs:
   First_Job:
    runs-on: ubuntu-latest
    steps:
	- name: Checkout
	  uses: actions/checkout@v4
	- name: compile java source
	  run: javac -d bin src/HelloWorld.java
	- name: Running
          run: java -cp bin helloWorld
