name: Demo
run-name: Github actions Demo

on:
  push:
    branches: [main]

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: compile java source
        run: javac -d bin src/HelloWorld.java
      - name: running
        run: java -cp bin HelloWorld
